spring.application.name=ManagingLibrary
server.port=8083
spring.datasource.url=jdbc:postgresql://localhost:5432/LibraryManagement
spring.datasource.username=postgres
spring.datasource.password=Est#4444

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
logging.level.org.springframework.security=TRACE

# JWT Configuration
jwt.secret=VGhpcyBpcyBhIHZhbGlkIHNlY3JldCBrZXkgZm9yIEpXVCB1c2luZyBIUzI1Ng==
jwt.expiration=86400000

# OAuth2 Client Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.jwk-set-uri=https://www.googleapis.com/oauth2/v3/certs

debug=true

